### ISSUE TITLE
Can't add flyout

### ISSUE THREAD

**Issue by edulorenzo** [timheuer/callisto#76]
Hi Tim,

Just downloaded and installed Callisto. When I drop a flyout control on a blank page (new project) it gives me exceptions and I can't use it.

Am using W8 RP, VS Express RC for W8

at Microsoft.Expression.Platform.InstanceBuilders.InstanceBuilderOperations.InstantiateType(Type type, Boolean supportInternal)
   at Microsoft.Expression.Platform.InstanceBuilders.ClrObjectInstanceBuilder.InstantiateTargetType(IInstanceBuilderContext context, ViewNode viewNode)
   at Microsoft.Expression.Platform.InstanceBuilders.ClrObjectInstanceBuilder.Instantiate(IInstanceBuilderContext context, ViewNode viewNode)
   at Microsoft.Expression.WindowsXamlPlatform.InstanceBuilders.FrameworkElementInstanceBuilder.Instantiate(IInstanceBuilderContext context, ViewNode viewNode)
   at Microsoft.Expression.Platform.InstanceBuilders.ViewNodeManager.CreateInstance(IInstanceBuilder builder, ViewNode viewNode)

   at Windows.UI.Xaml.Window.add_Activated(WindowActivatedEventHandler value)
   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.AddEventHandler[T](Func`2 addMethod, Action`1 removeMethod, T handler)
   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.AddEventHandler[T](Func`2 addMethod, Action`1 removeMethod, T handler)
   at Callisto.Controls.Flyout..ctor()

Thank you for giving attention to this. Thanks in advance!

**Comment by timheuer** [comment]
There is a known issue that Flyout doesn't work on the design surface given
the design of the control.  I've been working to change that but it would
result in a breaking change that I'm trying to prevent now.  In the
meantime, see the test app for an example usage.

**Comment by edulorenzo** [comment]
Thanks Tim.
